//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Repository.Pattern.Ef6;

namespace TransRoute.Entities.Db
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerAccounnt: Entity
    {
        public long Id { get; set; }
        public string AccountName { get; set; }
        public string AccountNo { get; set; }
        public string AccountType { get; set; }
        public string Bvn { get; set; }
        public Nullable<long> CustomerProfileId { get; set; }
        public System.DateTime DateCreated { get; set; }
    
        public virtual CustomerProfile CustomerProfile { get; set; }
    }
}
